# Generated by Django 4.2.3 on 2023-07-11 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='captured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='date_captured',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='description',
            field=models.TextField(default='None'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='level',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
