# Generated by Django 4.2.3 on 2023-07-12 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_app', '0003_alter_pokemon_date_captured_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='date_encountered',
            field=models.DateField(default='2008-01-01'),
        ),
    ]
