# Generated by Django 4.2.3 on 2023-07-12 17:25

from django.db import migrations, models
import pokemon_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_app', '0005_alter_pokemon_description_alter_pokemon_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='name',
            field=models.CharField(max_length=200, unique=True, validators=[pokemon_app.validators.validate_name]),
        ),
    ]
