# Generated by Django 4.2.3 on 2023-07-12 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('move_app', '0001_initial'),
        ('pokemon_app', '0006_alter_pokemon_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='moves',
            field=models.ManyToManyField(default=[1], to='move_app.move'),
        ),
    ]
