# Generated by Django 4.2.3 on 2023-07-12 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('move_app', '0001_initial'),
        ('pokemon_app', '0007_pokemon_moves'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='moves',
            field=models.ManyToManyField(default=1, to='move_app.move'),
        ),
    ]
